services:
  postgres:
    container_name: postgres_audit
    image: postgres:12.8
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=local
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
      - MAX_CONNECTIONS=300